name: Build latest

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: install needed
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: build os
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          name: MillaOS-ISO
          path: os.iso
